use bzip2::read::BzDecoder;
use regex::bytes::Regex;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::{self, BufReader, BufWriter, Read, Write};
use std::path::{Path, PathBuf};
use std::time::Duration;
use tar::Archive;
use walkdir::WalkDir;

const RELEASES_API: &str = "https://api.github.com/repos/Detanup01/gbe_fork/releases/latest";
const USER_AGENT: &str = "SteamManifestDownloader";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Variant {
    Regular,
    Experimental,
}

impl Variant {
    fn folder(self) -> &'static str {
        match self {
            Variant::Regular => "regular",
            Variant::Experimental => "experimental",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    Windows,
    Linux,
}

impl Platform {
    fn asset_name(self) -> &'static str {
        match self {
            Platform::Windows => "emu-win-release-vs26.7z",
            Platform::Linux => "emu-linux-release.tar.bz2",
        }
    }
    fn asset_match(
        self,
    ) -> (
        &'static str,
        &'static str,
        &'static [&'static str],
        &'static [&'static str],
    ) {
        match self {
            Platform::Windows => ("win", ".7z", &["release"], &["debug"]),
            Platform::Linux => ("linux", ".tar.bz2", &["release"], &["debug"]),
        }
    }
    pub fn cache_subdir(self) -> &'static str {
        match self {
            Platform::Windows => "windows",
            Platform::Linux => "linux",
        }
    }
    fn emu_filename(self, x64: bool) -> &'static str {
        match (self, x64) {
            (Platform::Windows, true) => "steam_api64.dll",
            (Platform::Windows, false) => "steam_api.dll",
            (Platform::Linux, _) => "libsteam_api.so",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleaseInfo {
    pub tag: String,
    pub published_at: String,
    pub windows_url: String,
    pub windows_size: u64,
    pub linux_url: String,
    pub linux_size: u64,
    pub windows_cached: bool,
    pub linux_cached: bool,
    pub cache_root: String,
    #[serde(default)]
    pub bundled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScannedFile {
    pub path: String,
    pub platform: Platform,
    pub arch: String,
    pub is_patched: bool,
}

pub mod fail {
    pub const EMU_BINARY_MISSING: &str = "emu_binary_missing";
    pub const INTERFACES_FAILED: &str = "interfaces_failed";
    pub const BACKUP_FAILED: &str = "backup_failed";
    pub const COPY_FAILED: &str = "copy_failed";
    pub const SETTINGS_WRITE_FAILED: &str = "settings_write_failed";
    pub const NO_PARENT_DIR: &str = "no_parent_dir";
    pub const FOLDER_MISSING: &str = "folder_missing";
    pub const NO_BACKUP: &str = "no_backup";
    pub const RESTORE_FAILED: &str = "restore_failed";
}

type TargetError = (&'static str, String);

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplaceResult {
    pub path: String,
    pub backup_path: Option<String>,
    pub success: bool,
    pub error: Option<String>,
    #[serde(default, rename = "failClass")]
    pub fail_class: Option<String>,
    #[serde(default, rename = "dlcCount", skip_serializing_if = "Option::is_none")]
    pub dlc_count: Option<usize>,
}

pub fn render_app_ini(dlcs: &[(String, String)]) -> String {
    let mut out = String::from(INI_HEADER);
    out.push_str("[app::dlcs]\nunlock_all=0\n");
    for (id, name) in dlcs {
        let name: String = name.chars().filter(|c| *c != '\n' && *c != '\r').collect();
        out.push_str(&format!("{}={}\n", id.trim(), name.trim()));
    }
    out
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct EmuSettings {
    pub account_name: Option<String>,
    pub account_steamid: Option<String>,
    pub language: Option<String>,
    pub ip_country: Option<String>,
    pub local_save_path: Option<String>,
    pub saves_folder_name: Option<String>,
    pub offline: Option<bool>,
    pub steam_deck: Option<bool>,
    pub disable_networking: Option<bool>,
    pub disable_lan_only: Option<bool>,
    pub record_playtime: Option<bool>,
    pub achievements_bypass: Option<bool>,
    pub force_steamhttp_success: Option<bool>,
    pub enable_steam_preowned_ids: Option<bool>,
    pub free_weekend: Option<bool>,
    pub enable_experimental_overlay: Option<bool>,
    pub disable_achievement_notification: Option<bool>,
    pub overlay_always_show_fps: Option<bool>,
    pub overlay_always_show_playtime: Option<bool>,
    pub key_combo: Option<String>,
    pub font_size: Option<f32>,
}

const INI_HEADER: &str = "# Generated by Steam Manifest Downloader.\n# Edit these settings via the in-app emulator step. Any keys not managed\n# here will be overwritten on re-apply.\n\n";

fn bool_to_ini(b: bool) -> &'static str {
    if b { "1" } else { "0" }
}

fn ini_from_bool(s: &str) -> Option<bool> {
    match s.trim() {
        "1" | "true" | "yes" | "on" => Some(true),
        "0" | "false" | "no" | "off" => Some(false),
        _ => None,
    }
}

fn parse_ini_sections(text: &str) -> std::collections::HashMap<String, std::collections::HashMap<String, String>> {
    let mut out: std::collections::HashMap<String, std::collections::HashMap<String, String>> =
        std::collections::HashMap::new();
    let mut current: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
            continue;
        }
        if line.starts_with('[') && line.ends_with(']') {
            current = Some(line[1..line.len() - 1].trim().to_string());
            continue;
        }
        let Some(section) = current.as_ref() else { continue };
        let Some(eq) = line.find('=') else { continue };
        let key = line[..eq].trim().to_string();
        let val = line[eq + 1..].trim().to_string();
        out.entry(section.clone()).or_default().insert(key, val);
    }
    out
}

impl EmuSettings {
    pub fn render_user_ini(&self) -> String {
        let mut sections: Vec<(String, Vec<(String, String)>)> = Vec::new();

        let mut general = Vec::new();
        if let Some(v) = &self.account_name { general.push(("account_name".into(), v.clone())); }
        if let Some(v) = &self.account_steamid { general.push(("account_steamid".into(), v.clone())); }
        if let Some(v) = &self.language { general.push(("language".into(), v.clone())); }
        if let Some(v) = &self.ip_country { general.push(("ip_country".into(), v.clone())); }
        if !general.is_empty() { sections.push(("user::general".into(), general)); }

        let mut saves = Vec::new();
        if let Some(v) = &self.local_save_path { saves.push(("local_save_path".into(), v.clone())); }
        if let Some(v) = &self.saves_folder_name { saves.push(("saves_folder_name".into(), v.clone())); }
        if !saves.is_empty() { sections.push(("user::saves".into(), saves)); }

        render_sections(&sections)
    }

    pub fn render_main_ini(&self) -> String {
        let mut sections: Vec<(String, Vec<(String, String)>)> = Vec::new();

        let mut general = Vec::new();
        if let Some(v) = self.offline { general.push(("offline".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.steam_deck { general.push(("steam_deck".into(), bool_to_ini(v).into())); }
        if !general.is_empty() { sections.push(("main::general".into(), general)); }

        let mut conn = Vec::new();
        if let Some(v) = self.disable_networking { conn.push(("disable_networking".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.disable_lan_only { conn.push(("disable_lan_only".into(), bool_to_ini(v).into())); }
        if !conn.is_empty() { sections.push(("main::connectivity".into(), conn)); }

        let mut stats = Vec::new();
        if let Some(v) = self.record_playtime { stats.push(("record_playtime".into(), bool_to_ini(v).into())); }
        if !stats.is_empty() { sections.push(("main::stats".into(), stats)); }

        let mut misc = Vec::new();
        if let Some(v) = self.achievements_bypass { misc.push(("achievements_bypass".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.force_steamhttp_success { misc.push(("force_steamhttp_success".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.enable_steam_preowned_ids { misc.push(("enable_steam_preowned_ids".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.free_weekend { misc.push(("free_weekend".into(), bool_to_ini(v).into())); }
        if !misc.is_empty() { sections.push(("main::misc".into(), misc)); }

        render_sections(&sections)
    }

    pub fn render_overlay_ini(&self) -> String {
        let mut sections: Vec<(String, Vec<(String, String)>)> = Vec::new();

        let mut general = Vec::new();
        if let Some(v) = self.enable_experimental_overlay { general.push(("enable_experimental_overlay".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.disable_achievement_notification { general.push(("disable_achievement_notification".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.overlay_always_show_fps { general.push(("overlay_always_show_fps".into(), bool_to_ini(v).into())); }
        if let Some(v) = self.overlay_always_show_playtime { general.push(("overlay_always_show_playtime".into(), bool_to_ini(v).into())); }
        if !general.is_empty() { sections.push(("overlay::general".into(), general)); }

        let mut hotkeys = Vec::new();
        if let Some(v) = &self.key_combo { hotkeys.push(("key_combo".into(), v.clone())); }
        if !hotkeys.is_empty() { sections.push(("overlay::hotkeys".into(), hotkeys)); }

        let mut appearance = Vec::new();
        if let Some(v) = self.font_size { appearance.push(("Font_Size".into(), format!("{}", v))); }
        if !appearance.is_empty() { sections.push(("overlay::appearance".into(), appearance)); }

        render_sections(&sections)
    }

    pub fn write_to_dir(&self, dir: &Path) -> Result<(), String> {
        fs::create_dir_all(dir).map_err(|e| format!("create steam_settings: {}", e))?;
        let write_or_remove = |name: &str, content: String| -> Result<(), String> {
            let path = dir.join(name);
            if content.trim().is_empty() {
                let _ = fs::remove_file(&path);
                return Ok(());
            }
            fs::write(&path, content).map_err(|e| format!("write {}: {}", name, e))
        };
        write_or_remove("configs.user.ini", self.render_user_ini())?;
        write_or_remove("configs.main.ini", self.render_main_ini())?;
        write_or_remove("configs.overlay.ini", self.render_overlay_ini())?;
        Ok(())
    }

    pub fn read_from_dir(dir: &Path) -> EmuSettings {
        let mut s = EmuSettings::default();
        if let Ok(text) = fs::read_to_string(dir.join("configs.user.ini")) {
            s.absorb_user(&text);
        }
        if let Ok(text) = fs::read_to_string(dir.join("configs.main.ini")) {
            s.absorb_main(&text);
        }
        if let Ok(text) = fs::read_to_string(dir.join("configs.overlay.ini")) {
            s.absorb_overlay(&text);
        }
        s
    }

    fn absorb_user(&mut self, text: &str) {
        let parsed = parse_ini_sections(text);
        if let Some(sec) = parsed.get("user::general") {
            if let Some(v) = sec.get("account_name") { self.account_name = Some(v.clone()); }
            if let Some(v) = sec.get("account_steamid") { self.account_steamid = Some(v.clone()); }
            if let Some(v) = sec.get("language") { self.language = Some(v.clone()); }
            if let Some(v) = sec.get("ip_country") { self.ip_country = Some(v.clone()); }
        }
        if let Some(sec) = parsed.get("user::saves") {
            if let Some(v) = sec.get("local_save_path") { self.local_save_path = Some(v.clone()); }
            if let Some(v) = sec.get("saves_folder_name") { self.saves_folder_name = Some(v.clone()); }
        }
    }

    fn absorb_main(&mut self, text: &str) {
        let parsed = parse_ini_sections(text);
        if let Some(sec) = parsed.get("main::general") {
            if let Some(v) = sec.get("offline") { self.offline = ini_from_bool(v); }
            if let Some(v) = sec.get("steam_deck") { self.steam_deck = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("main::connectivity") {
            if let Some(v) = sec.get("disable_networking") { self.disable_networking = ini_from_bool(v); }
            if let Some(v) = sec.get("disable_lan_only") { self.disable_lan_only = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("main::stats") {
            if let Some(v) = sec.get("record_playtime") { self.record_playtime = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("main::misc") {
            if let Some(v) = sec.get("achievements_bypass") { self.achievements_bypass = ini_from_bool(v); }
            if let Some(v) = sec.get("force_steamhttp_success") { self.force_steamhttp_success = ini_from_bool(v); }
            if let Some(v) = sec.get("enable_steam_preowned_ids") { self.enable_steam_preowned_ids = ini_from_bool(v); }
            if let Some(v) = sec.get("free_weekend") { self.free_weekend = ini_from_bool(v); }
        }
    }

    fn absorb_overlay(&mut self, text: &str) {
        let parsed = parse_ini_sections(text);
        if let Some(sec) = parsed.get("overlay::general") {
            if let Some(v) = sec.get("enable_experimental_overlay") { self.enable_experimental_overlay = ini_from_bool(v); }
            if let Some(v) = sec.get("disable_achievement_notification") { self.disable_achievement_notification = ini_from_bool(v); }
            if let Some(v) = sec.get("overlay_always_show_fps") { self.overlay_always_show_fps = ini_from_bool(v); }
            if let Some(v) = sec.get("overlay_always_show_playtime") { self.overlay_always_show_playtime = ini_from_bool(v); }
        }
        if let Some(sec) = parsed.get("overlay::hotkeys") {
            if let Some(v) = sec.get("key_combo") { self.key_combo = Some(v.clone()); }
        }
        if let Some(sec) = parsed.get("overlay::appearance") {
            if let Some(v) = sec.get("Font_Size") {
                if let Ok(n) = v.parse::<f32>() { self.font_size = Some(n); }
            }
        }
    }
}

fn render_sections(sections: &[(String, Vec<(String, String)>)]) -> String {
    if sections.is_empty() {
        return String::new();
    }
    let mut out = String::from(INI_HEADER);
    for (i, (name, kvs)) in sections.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push('[');
        out.push_str(name);
        out.push_str("]\n");
        for (k, v) in kvs {
            out.push_str(k);
            out.push('=');
            out.push_str(v);
            out.push('\n');
        }
    }
    out
}

fn cache_root(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("gbe_fork_cache")
}

fn vs_number(name: &str) -> Option<u32> {
    let lower = name.to_lowercase();
    let mut best: Option<u32> = None;
    let mut search = lower.as_str();
    while let Some(pos) = search.find("vs") {
        let rest = &search[pos + 2..];
        let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
        if let Ok(n) = digits.parse::<u32>() {
            best = Some(best.map_or(n, |b| b.max(n)));
        }
        search = rest;
    }
    best
}

fn pick_asset<'a>(
    assets: &'a [serde_json::Value],
    name: &str,
    keyword: &str,
    extension: &str,
    required: &[&str],
    excluded: &[&str],
) -> Result<&'a serde_json::Value, String> {
    let mut candidates: Vec<&serde_json::Value> = assets
        .iter()
        .filter(|a| {
            a.get("name").and_then(|v| v.as_str()).is_some_and(|n| {
                let lower = n.to_lowercase();
                lower.contains(keyword)
                    && lower.ends_with(extension)
                    && required.iter().all(|r| lower.contains(r))
                    && !excluded.iter().any(|x| lower.contains(x))
            })
        })
        .collect();
    candidates.sort_by_key(|a| {
        let n = a.get("name").and_then(|v| v.as_str()).and_then(vs_number);
        (n.is_none(), n.map(std::cmp::Reverse))
    });
    if let Some(a) = candidates.iter().find(|a| {
        a.get("name")
            .and_then(|v| v.as_str())
            .and_then(vs_number)
            .is_some()
    }) {
        return Ok(a);
    }
    if let Some(a) = assets
        .iter()
        .find(|a| a.get("name").and_then(|v| v.as_str()) == Some(name))
    {
        return Ok(a);
    }
    if let Some(a) = candidates.into_iter().next() {
        return Ok(a);
    }
    let available: Vec<String> = assets
        .iter()
        .filter_map(|a| {
            a.get("name")
                .and_then(|v| v.as_str())
                .map(str::to_string)
        })
        .collect();
    Err(format!(
        "Asset {} not present in release (available: {})",
        name,
        if available.is_empty() {
            "none".to_string()
        } else {
            available.join(", ")
        }
    ))
}

#[derive(Debug, Deserialize)]
struct BundledRelease {
    tag: String,
    #[serde(default)]
    published_at: String,
    windows: String,
    linux: String,
}

fn bundled_release_info(app_data_dir: &Path) -> Option<ReleaseInfo> {
    let manifest = crate::paths::bundled_file(&["gbe_fork", "release.json"])?;
    let dir = manifest.parent()?.to_path_buf();
    let release: BundledRelease = serde_json::from_slice(&fs::read(&manifest).ok()?).ok()?;
    let windows = dir.join(&release.windows);
    let linux = dir.join(&release.linux);
    let windows_size = fs::metadata(&windows).ok().filter(|m| m.is_file())?.len();
    let linux_size = fs::metadata(&linux).ok().filter(|m| m.is_file())?.len();
    let root = cache_root(app_data_dir).join(&release.tag);
    Some(ReleaseInfo {
        windows_cached: root
            .join(Platform::Windows.cache_subdir())
            .join(".extracted")
            .exists(),
        linux_cached: root
            .join(Platform::Linux.cache_subdir())
            .join(".extracted")
            .exists(),
        tag: release.tag,
        published_at: release.published_at,
        windows_url: windows.to_string_lossy().to_string(),
        windows_size,
        linux_url: linux.to_string_lossy().to_string(),
        linux_size,
        cache_root: root.to_string_lossy().to_string(),
        bundled: true,
    })
}

pub async fn fetch_release_info(client: &Client, app_data_dir: &Path) -> Result<ReleaseInfo, String> {
    if let Some(info) = bundled_release_info(app_data_dir) {
        return Ok(info);
    }
    let resp = client
        .get(RELEASES_API)
        .header("User-Agent", USER_AGENT)
        .header("Accept", "application/vnd.github+json")
        .timeout(Duration::from_secs(30))
        .send()
        .await
        .map_err(|e| format!("GitHub fetch failed: {}", e))?;

    if !resp.status().is_success() {
        return Err(format!("GitHub returned HTTP {}", resp.status()));
    }

    let body: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| format!("GitHub JSON parse failed: {}", e))?;

    let tag = body
        .get("tag_name")
        .and_then(|v| v.as_str())
        .ok_or("Missing tag_name in release info")?
        .to_string();
    let published_at = body
        .get("published_at")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    let assets = body
        .get("assets")
        .and_then(|v| v.as_array())
        .ok_or("Missing assets array")?;

    let pick = |platform: Platform| -> Result<(String, u64), String> {
        let name = platform.asset_name();
        let (keyword, extension, required, excluded) = platform.asset_match();
        let a = pick_asset(assets, name, keyword, extension, required, excluded)?;
        let url = a
            .get("browser_download_url")
            .and_then(|v| v.as_str())
            .ok_or("Asset has no browser_download_url")?
            .to_string();
        let size = a.get("size").and_then(|v| v.as_u64()).unwrap_or(0);
        Ok((url, size))
    };

    let (windows_url, windows_size) = pick(Platform::Windows)?;
    let (linux_url, linux_size) = pick(Platform::Linux)?;

    let root = cache_root(app_data_dir).join(&tag);
    let windows_cached = root.join(Platform::Windows.cache_subdir()).join(".extracted").exists();
    let linux_cached = root.join(Platform::Linux.cache_subdir()).join(".extracted").exists();

    Ok(ReleaseInfo {
        tag,
        published_at,
        windows_url,
        windows_size,
        linux_url,
        linux_size,
        windows_cached,
        linux_cached,
        cache_root: root.to_string_lossy().to_string(),
        bundled: false,
    })
}

pub fn platform_cached(info: &ReleaseInfo, platform: Platform) -> bool {
    PathBuf::from(&info.cache_root)
        .join(platform.cache_subdir())
        .join(".extracted")
        .exists()
}

fn prune_keep(name: &str) -> bool {
    let lower = name.to_lowercase();
    lower == ".extracted"
        || lower.ends_with(".dll")
        || lower.ends_with(".so")
        || lower.contains(".so.")
}

fn prune_platform_dir(dir: &Path) {
    for entry in WalkDir::new(dir)
        .min_depth(1)
        .contents_first(true)
        .into_iter()
        .flatten()
    {
        let path = entry.path();
        if path.is_file() {
            let keep = path
                .file_name()
                .and_then(|n| n.to_str())
                .is_some_and(prune_keep);
            if !keep {
                let _ = fs::remove_file(path);
            }
        } else if path != dir {
            let _ = fs::remove_dir(path);
        }
    }
}

pub async fn ensure_cached(
    client: &Client,
    info: &ReleaseInfo,
    platform: Platform,
    on_progress: impl Fn(u64, u64) + Send + Sync,
) -> Result<PathBuf, String> {
    let platform_dir = PathBuf::from(&info.cache_root).join(platform.cache_subdir());
    let extracted_marker = platform_dir.join(".extracted");
    if extracted_marker.exists() {
        prune_platform_dir(&platform_dir);
        return Ok(platform_dir);
    }

    fs::create_dir_all(&platform_dir).map_err(|e| format!("create cache dir: {}", e))?;
    let asset_name = platform.asset_name();
    let asset_url = match platform {
        Platform::Windows => &info.windows_url,
        Platform::Linux => &info.linux_url,
    };
    let archive_path = platform_dir.join(asset_name);

    if !archive_path.exists() && info.bundled {
        fs::copy(asset_url, &archive_path)
            .map_err(|e| format!("copy bundled archive {}: {}", asset_url, e))?;
        let size = fs::metadata(&archive_path).map(|m| m.len()).unwrap_or(0);
        on_progress(size, size);
    }
    if !archive_path.exists() {
        let mut resp = client
            .get(asset_url)
            .header("User-Agent", USER_AGENT)
            .timeout(Duration::from_secs(600))
            .send()
            .await
            .map_err(|e| format!("download failed: {}", e))?;
        if !resp.status().is_success() {
            return Err(format!("download returned HTTP {}", resp.status()));
        }
        let total = match platform {
            Platform::Windows => info.windows_size,
            Platform::Linux => info.linux_size,
        };
        let tmp_path = platform_dir.join(format!("{}.part", asset_name));
        {
            let mut file =
                BufWriter::new(File::create(&tmp_path).map_err(|e| format!("create archive: {}", e))?);
            let mut downloaded: u64 = 0;
            let mut next_emit_at: u64 = 1024 * 1024;
            while let Some(chunk) = resp.chunk().await.map_err(|e| format!("chunk: {}", e))? {
                file.write_all(&chunk).map_err(|e| format!("write archive: {}", e))?;
                downloaded += chunk.len() as u64;
                if downloaded >= next_emit_at {
                    next_emit_at += 1024 * 1024;
                    on_progress(downloaded, total);
                }
            }
            file.flush().map_err(|e| format!("flush archive: {}", e))?;
            on_progress(downloaded, total);
        }
        fs::rename(&tmp_path, &archive_path).map_err(|e| format!("finalize archive: {}", e))?;
    }

    if let Err(e) = extract_archive(&archive_path, &platform_dir, platform) {
        if e.starts_with("AV_BLOCKED") {
            let _ = fs::remove_file(&archive_path);
        }
        return Err(e);
    }
    let _ = fs::remove_file(&archive_path);
    prune_platform_dir(&platform_dir);
    fs::write(&extracted_marker, info.tag.as_bytes())
        .map_err(|e| format!("write extracted marker: {}", e))?;

    Ok(platform_dir)
}

fn extract_archive(archive: &Path, dst: &Path, platform: Platform) -> Result<(), String> {
    match platform {
        Platform::Linux => extract_tar_bz2(archive, dst),
        Platform::Windows => extract_7z(archive, dst),
    }
}

fn extract_tar_bz2(archive: &Path, dst: &Path) -> Result<(), String> {
    let file = File::open(archive).map_err(|e| format!("open archive: {}", e))?;
    let mut decoder = BzDecoder::new(BufReader::new(file));
    let mut tmp = Vec::with_capacity(64 * 1024 * 1024);
    decoder
        .read_to_end(&mut tmp)
        .map_err(|e| format!("bzip2 decompress: {}", e))?;
    let mut tar = Archive::new(io::Cursor::new(tmp));
    tar.unpack(dst).map_err(|e| format!("tar unpack: {}", e))?;
    Ok(())
}

fn extract_7z(archive: &Path, dst: &Path) -> Result<(), String> {
    sevenz_rust::decompress_file(archive, dst).map_err(|e| {
        let msg = e.to_string();
        if is_antivirus_block(&msg) {
            format!("AV_BLOCKED: {}", msg)
        } else {
            format!("7z decompress: {}", msg)
        }
    })
}

fn is_antivirus_block(msg: &str) -> bool {
    let lower = msg.to_lowercase();
    msg.contains("code: 225")
        || lower.contains("virus")
        || lower.contains("unerwünschte software")
        || lower.contains("unwanted software")
}

fn arch_dirs(x64: bool) -> &'static [&'static str] {
    if x64 {
        &["x64"]
    } else {
        &["x86", "x32"]
    }
}

fn build_trees() -> &'static [&'static str] {
    &["release", "debug"]
}

pub fn dll_source(
    platform_cache: &Path,
    variant: Variant,
    x64: bool,
    platform: Platform,
) -> Result<PathBuf, String> {
    let filename = platform.emu_filename(x64);
    let mut tried = Vec::new();
    for tree in build_trees() {
        let root = platform_cache.join(tree).join(variant.folder());
        for dir in arch_dirs(x64) {
            let p = root.join(dir).join(filename);
            if p.exists() {
                return Ok(p);
            }
            tried.push(p.display().to_string());
        }
    }
    Err(format!("emulator binary not found, tried: {}", tried.join(", ")))
}

pub fn scan_game_dir(game_dir: &Path) -> Vec<ScannedFile> {
    let mut out = Vec::new();
    if !game_dir.exists() {
        return out;
    }
    for entry in WalkDir::new(game_dir).follow_links(false).into_iter().flatten() {
        if !entry.file_type().is_file() {
            continue;
        }
        let name = entry.file_name().to_string_lossy().to_ascii_lowercase();
        let (platform, arch) = if name == "steam_api64.dll" {
            (Platform::Windows, "x64")
        } else if name == "steam_api.dll" {
            (Platform::Windows, "x32")
        } else if name == "libsteam_api.so" {
            (Platform::Linux, detect_so_arch(entry.path()))
        } else {
            continue;
        };
        let is_patched = backup_path_for(entry.path()).exists();
        out.push(ScannedFile {
            path: entry.path().to_string_lossy().to_string(),
            platform,
            arch: arch.to_string(),
            is_patched,
        });
    }
    out
}

fn detect_so_arch(path: &Path) -> &'static str {
    let Ok(mut file) = File::open(path) else {
        return "x64";
    };
    let mut header = [0u8; 5];
    if file.read_exact(&mut header).is_err() {
        return "x64";
    }
    if &header[..4] != b"\x7fELF" {
        return "x64";
    }
    match header[4] {
        1 => "x32",
        2 => "x64",
        _ => "x64",
    }
}

const INTERFACE_PATTERNS: &[&str] = &[
    r"STEAMAPPS_INTERFACE_VERSION\d+",
    r"SteamApps\d+",
    r"STEAMAPPLIST_INTERFACE_VERSION\d+",
    r"STEAMAPPTICKET_INTERFACE_VERSION\d+",
    r"SteamClient\d+",
    r"STEAMCONTROLLER_INTERFACE_VERSION",
    r"SteamController\d+",
    r"SteamFriends\d+",
    r"SteamGameServerStats\d+",
    r"SteamGameCoordinator\d+",
    r"SteamGameServer\d+",
    r"STEAMHTMLSURFACE_INTERFACE_VERSION_\d+",
    r"STEAMHTTP_INTERFACE_VERSION\d+",
    r"SteamInput\d+",
    r"STEAMINVENTORY_INTERFACE_V\d+",
    r"SteamMatchMakingServers\d+",
    r"SteamMatchMaking\d+",
    r"SteamMatchGameSearch\d+",
    r"SteamParties\d+",
    r"STEAMMUSIC_INTERFACE_VERSION\d+",
    r"STEAMMUSICREMOTE_INTERFACE_VERSION\d+",
    r"SteamNetworkingMessages\d+",
    r"SteamNetworkingSockets\d+",
    r"SteamNetworkingUtils\d+",
    r"SteamNetworking\d+",
    r"STEAMPARENTALSETTINGS_INTERFACE_VERSION\d+",
    r"STEAMREMOTEPLAY_INTERFACE_VERSION\d+",
    r"STEAMREMOTESTORAGE_INTERFACE_VERSION\d+",
    r"STEAMSCREENSHOTS_INTERFACE_VERSION\d+",
    r"STEAMTIMELINE_INTERFACE_V\d+",
    r"STEAMUGC_INTERFACE_VERSION\d+",
    r"SteamUser\d+",
    r"STEAMUSERSTATS_INTERFACE_VERSION\d+",
    r"SteamUtils\d+",
    r"STEAMVIDEO_INTERFACE_V\d+",
    r"STEAMUNIFIEDMESSAGES_INTERFACE_VERSION\d+",
    r"SteamMasterServerUpdater\d+",
];

pub fn generate_interfaces(dll_bytes: &[u8]) -> Result<String, String> {
    let mut out = String::new();
    let mut total: usize = 0;
    for patt in INTERFACE_PATTERNS {
        let re = Regex::new(patt).map_err(|e| format!("bad pattern '{}': {}", patt, e))?;
        let mut matches: Vec<Vec<u8>> = re
            .find_iter(dll_bytes)
            .map(|m| m.as_bytes().to_vec())
            .collect();

        if *patt == r"SteamClient\d+" && matches.len() > 1 {
            let has_017 = matches.iter().any(|m| m == b"SteamClient017");
            if has_017 {
                matches.retain(|m| m == b"SteamClient017");
            }
        }

        for m in matches {
            if let Ok(s) = std::str::from_utf8(&m) {
                out.push_str(s);
                out.push('\n');
                total += 1;
            }
        }
    }
    if total == 0 {
        return Err("No Steam interfaces found in the binary".into());
    }
    Ok(out)
}

fn generate_interfaces_from_file(target: &Path) -> Result<String, String> {
    let bytes = fs::read(target).map_err(|e| format!("read {}: {}", target.display(), e))?;
    generate_interfaces(&bytes)
}

pub fn apply_replacement(
    target: &Path,
    platform_cache: &Path,
    variant: Variant,
    platform: Platform,
    x64: bool,
    app_id: &str,
    installed_app_ids: &[String],
    emu_settings: Option<&EmuSettings>,
    dlcs: Option<&[(String, String)]>,
) -> ReplaceResult {
    let mut result = ReplaceResult {
        path: target.to_string_lossy().to_string(),
        backup_path: None,
        success: false,
        error: None,
        fail_class: None,
        dlc_count: None,
    };
    crate::dlog!(
        "emu",
        "apply start target={} platform={:?} arch={} variant={:?}",
        target.display(),
        platform,
        if x64 { "x64" } else { "x32" },
        variant
    );
    match apply_to_target(
        target,
        platform_cache,
        variant,
        platform,
        x64,
        app_id,
        installed_app_ids,
        emu_settings,
        dlcs,
        &mut result,
    ) {
        Ok(()) => {
            result.success = true;
            crate::dlog!("emu", "apply ok target={}", target.display());
        }
        Err((class, e)) => {
            crate::dlog!(
                "emu",
                "apply FAILED target={} class={} reason={}",
                target.display(),
                class,
                e
            );
            result.fail_class = Some(class.to_string());
            result.error = Some(e);
        }
    }
    result
}

fn apply_to_target(
    target: &Path,
    platform_cache: &Path,
    variant: Variant,
    platform: Platform,
    x64: bool,
    app_id: &str,
    installed_app_ids: &[String],
    emu_settings: Option<&EmuSettings>,
    dlcs: Option<&[(String, String)]>,
    result: &mut ReplaceResult,
) -> Result<(), TargetError> {
    let emu_dll = dll_source(platform_cache, variant, x64, platform)
        .map_err(|e| (fail::EMU_BINARY_MISSING, e))?;
    crate::dlog!("emu", "emulator binary resolved: {}", emu_dll.display());

    let interfaces_source = interfaces_source_for(target);
    crate::dlog!(
        "emu",
        "reading interfaces from {} (backup={})",
        interfaces_source.display(),
        interfaces_source != target
    );
    let interfaces = generate_interfaces_from_file(&interfaces_source)
        .map_err(|e| (fail::INTERFACES_FAILED, format!("generate_interfaces failed: {}", e)))?;

    let backup = backup_path_for(target);
    if backup.exists() {
        crate::dlog!("emu", "backup already present: {}", backup.display());
    } else {
        fs::copy(target, &backup)
            .map_err(|e| (fail::BACKUP_FAILED, format!("backup original: {}", e)))?;
        crate::dlog!("emu", "backup created: {}", backup.display());
    }
    result.backup_path = Some(backup.to_string_lossy().to_string());

    fs::copy(&emu_dll, target)
        .map_err(|e| (fail::COPY_FAILED, format!("copy emulator binary: {}", e)))?;

    let parent = target
        .parent()
        .ok_or((fail::NO_PARENT_DIR, "target has no parent dir".to_string()))?;
    let settings_dir = parent.join("steam_settings");
    fs::create_dir_all(&settings_dir)
        .map_err(|e| (fail::SETTINGS_WRITE_FAILED, format!("create steam_settings: {}", e)))?;

    fs::write(settings_dir.join("steam_interfaces.txt"), interfaces).map_err(|e| {
        (fail::SETTINGS_WRITE_FAILED, format!("write steam_interfaces.txt: {}", e))
    })?;
    fs::write(settings_dir.join("steam_appid.txt"), app_id.trim()).map_err(|e| {
        (fail::SETTINGS_WRITE_FAILED, format!("write steam_appid.txt: {}", e))
    })?;
    if !installed_app_ids.is_empty() {
        let joined = installed_app_ids
            .iter()
            .map(|s| s.trim())
            .filter(|s| !s.is_empty())
            .collect::<Vec<_>>()
            .join("\n");
        fs::write(settings_dir.join("installed_app_ids.txt"), joined).map_err(|e| {
            (fail::SETTINGS_WRITE_FAILED, format!("write installed_app_ids.txt: {}", e))
        })?;
    }

    if let Some(list) = dlcs {
        fs::write(settings_dir.join("configs.app.ini"), render_app_ini(list)).map_err(|e| {
            (fail::SETTINGS_WRITE_FAILED, format!("write configs.app.ini: {}", e))
        })?;
        result.dlc_count = Some(list.len());
    }

    if let Some(s) = emu_settings {
        s.write_to_dir(&settings_dir)
            .map_err(|e| (fail::SETTINGS_WRITE_FAILED, format!("write emu settings: {}", e)))?;
    }
    Ok(())
}

pub fn read_emu_settings_for_target(target: &Path) -> Result<EmuSettings, String> {
    let parent = target
        .parent()
        .ok_or_else(|| "target has no parent dir".to_string())?;
    let settings_dir = parent.join("steam_settings");
    Ok(EmuSettings::read_from_dir(&settings_dir))
}

pub fn write_emu_settings_for_target(target: &Path, settings: &EmuSettings) -> Result<(), String> {
    let parent = target
        .parent()
        .ok_or_else(|| "target has no parent dir".to_string())?;
    if !parent.exists() {
        return Err(format!("game folder not found: {}", parent.display()));
    }
    let settings_dir = parent.join("steam_settings");
    fs::create_dir_all(&settings_dir).map_err(|e| format!("create steam_settings: {}", e))?;
    settings.write_to_dir(&settings_dir)
}

pub fn revert_replacement(target: &Path) -> Result<(), TargetError> {
    if let Some(parent) = target.parent() {
        if !parent.exists() {
            return Err((
                fail::FOLDER_MISSING,
                format!("game folder not found: {}", parent.display()),
            ));
        }
    }
    let backup = backup_path_for(target);
    if !backup.exists() {
        return Err((
            fail::NO_BACKUP,
            format!("no backup found at {}", backup.display()),
        ));
    }
    fs::copy(&backup, target)
        .map_err(|e| (fail::RESTORE_FAILED, format!("restore from backup: {}", e)))?;
    let _ = fs::remove_file(&backup);
    if let Some(parent) = target.parent() {
        let settings_dir = parent.join("steam_settings");
        let _ = fs::remove_file(settings_dir.join("steam_interfaces.txt"));
        let _ = fs::remove_file(settings_dir.join("steam_appid.txt"));
        let _ = fs::remove_file(settings_dir.join("installed_app_ids.txt"));
        let _ = fs::remove_file(settings_dir.join("configs.app.ini"));
        let _ = fs::remove_dir(&settings_dir);
    }
    Ok(())
}

fn interfaces_source_for(target: &Path) -> PathBuf {
    let backup = backup_path_for(target);
    if backup.exists() {
        backup
    } else {
        target.to_path_buf()
    }
}

fn backup_path_for(target: &Path) -> PathBuf {
    let mut p = target.as_os_str().to_owned();
    p.push(".steam.bak");
    PathBuf::from(p)
}

#[cfg(test)]
mod bundled_tests {
    use super::*;

    #[test]
    fn bundled_release_is_used_without_network() {
        let tmp = std::env::temp_dir().join(format!("smd-bundled-{}", std::process::id()));
        let gbe = tmp.join("gbe_fork");
        fs::create_dir_all(&gbe).unwrap();
        fs::write(gbe.join("emu-win-release.7z"), b"win").unwrap();
        fs::write(gbe.join("emu-linux-release.tar.bz2"), b"linux!").unwrap();
        fs::write(
            gbe.join("release.json"),
            br#"{"tag":"release-test","windows":"emu-win-release.7z","linux":"emu-linux-release.tar.bz2"}"#,
        )
        .unwrap();
        std::env::set_var(crate::paths::BUNDLED_DIR_ENV, &tmp);
        let info = bundled_release_info(&tmp.join("data"));
        std::env::remove_var(crate::paths::BUNDLED_DIR_ENV);
        let info = info.expect("bundled release");
        assert!(info.bundled);
        assert_eq!(info.tag, "release-test");
        assert_eq!(info.windows_size, 3);
        assert_eq!(info.linux_size, 6);
        assert!(info.windows_url.ends_with("emu-win-release.7z"));
        assert!(!info.windows_cached);
        let _ = fs::remove_dir_all(&tmp);
    }
}

#[cfg(test)]
mod interfaces_source_tests {
    use super::*;

    #[test]
    fn a_first_patch_reads_the_library_itself() {
        let dir = std::env::temp_dir().join("smd-iface-first");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let target = dir.join("steam_api64.dll");
        fs::write(&target, b"original").unwrap();

        assert_eq!(interfaces_source_for(&target), target);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_repeat_patch_reads_the_backup_not_the_emulator() {
        let dir = std::env::temp_dir().join("smd-iface-repeat");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let target = dir.join("steam_api64.dll");
        fs::write(&target, b"gbe_fork").unwrap();
        let backup = backup_path_for(&target);
        fs::write(&backup, b"original").unwrap();

        let src = interfaces_source_for(&target);
        assert_eq!(src, backup);
        assert_eq!(fs::read(&src).unwrap(), b"original");
        let _ = fs::remove_dir_all(&dir);
    }
}

#[cfg(test)]
mod dll_source_tests {
    use super::*;

    fn cache_with(name: &str, arch: &str, file: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("smd-dllsrc-{}", name));
        let _ = fs::remove_dir_all(&dir);
        let leaf = dir.join("release").join("regular").join(arch);
        fs::create_dir_all(&leaf).unwrap();
        fs::write(leaf.join(file), b"emu").unwrap();
        dir
    }

    #[test]
    fn resolves_x86_layout_used_by_current_gbe_fork() {
        let cache = cache_with("x86", "x86", "steam_api.dll");
        let got = dll_source(&cache, Variant::Regular, false, Platform::Windows).unwrap();
        assert_eq!(got, cache.join("release/regular/x86/steam_api.dll"));
        let _ = fs::remove_dir_all(&cache);
    }

    #[test]
    fn still_resolves_legacy_x32_layout() {
        let cache = cache_with("x32", "x32", "steam_api.dll");
        let got = dll_source(&cache, Variant::Regular, false, Platform::Windows).unwrap();
        assert_eq!(got, cache.join("release/regular/x32/steam_api.dll"));
        let _ = fs::remove_dir_all(&cache);
    }

    #[test]
    fn resolves_linux_x86_layout() {
        let cache = cache_with("linux", "x86", "libsteam_api.so");
        let got = dll_source(&cache, Variant::Regular, false, Platform::Linux).unwrap();
        assert_eq!(got, cache.join("release/regular/x86/libsteam_api.so"));
        let _ = fs::remove_dir_all(&cache);
    }

    #[test]
    fn sixty_four_bit_is_unaffected() {
        let cache = cache_with("x64", "x64", "steam_api64.dll");
        let got = dll_source(&cache, Variant::Regular, true, Platform::Windows).unwrap();
        assert_eq!(got, cache.join("release/regular/x64/steam_api64.dll"));
        let _ = fs::remove_dir_all(&cache);
    }

    #[test]
    fn a_missing_emulator_binary_is_classified_not_guessed() {
        let dir = std::env::temp_dir().join("smd-failclass-binary");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let target = dir.join("steam_api.dll");
        fs::write(&target, b"original").unwrap();

        let r = apply_replacement(
            &target,
            &dir,
            Variant::Regular,
            Platform::Windows,
            false,
            "480",
            &[],
            None,
            None,
        );
        assert!(!r.success);
        assert_eq!(r.fail_class.as_deref(), Some(fail::EMU_BINARY_MISSING));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn reverting_without_a_backup_is_classified_no_backup() {
        let dir = std::env::temp_dir().join("smd-failclass-revert");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let target = dir.join("steam_api64.dll");
        fs::write(&target, b"patched").unwrap();

        let err = revert_replacement(&target).unwrap_err();
        assert_eq!(err.0, fail::NO_BACKUP);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn every_fail_class_is_a_lowercase_label_without_paths() {
        for class in [
            fail::EMU_BINARY_MISSING,
            fail::INTERFACES_FAILED,
            fail::BACKUP_FAILED,
            fail::COPY_FAILED,
            fail::SETTINGS_WRITE_FAILED,
            fail::NO_PARENT_DIR,
            fail::FOLDER_MISSING,
            fail::NO_BACKUP,
            fail::RESTORE_FAILED,
        ] {
            assert!(
                class.chars().all(|c| c.is_ascii_lowercase() || c == '_'),
                "{} is not a plain label",
                class
            );
        }
    }

    #[test]
    fn missing_binary_names_every_path_tried() {
        let cache = cache_with("missing", "x64", "steam_api64.dll");
        let err = dll_source(&cache, Variant::Regular, false, Platform::Windows).unwrap_err();
        assert!(err.contains("x86"), "{}", err);
        assert!(err.contains("x32"), "{}", err);
        let _ = fs::remove_dir_all(&cache);
    }

    fn cache_with_tree(name: &str, tree: &str, arch: &str, file: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("smd-dllsrc-{}", name));
        let _ = fs::remove_dir_all(&dir);
        let leaf = dir.join(tree).join("regular").join(arch);
        fs::create_dir_all(&leaf).unwrap();
        fs::write(leaf.join(file), b"emu").unwrap();
        dir
    }

    #[test]
    fn resolves_debug_tree_when_release_tree_is_absent() {
        let cache = cache_with_tree("debugonly", "debug", "x64", "steam_api64.dll");
        let got = dll_source(&cache, Variant::Regular, true, Platform::Windows).unwrap();
        assert_eq!(got, cache.join("debug/regular/x64/steam_api64.dll"));
        let _ = fs::remove_dir_all(&cache);
    }

    #[test]
    fn release_tree_wins_over_debug_tree() {
        let dir = std::env::temp_dir().join("smd-dllsrc-bothtrees");
        let _ = fs::remove_dir_all(&dir);
        for tree in ["release", "debug"] {
            let leaf = dir.join(tree).join("regular").join("x64");
            fs::create_dir_all(&leaf).unwrap();
            fs::write(leaf.join("steam_api64.dll"), b"emu").unwrap();
        }
        let got = dll_source(&dir, Variant::Regular, true, Platform::Windows).unwrap();
        assert_eq!(got, dir.join("release/regular/x64/steam_api64.dll"));
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn missing_binary_names_paths_from_both_trees() {
        let cache = cache_with("missingboth", "x64", "unrelated.dll");
        let err = dll_source(&cache, Variant::Regular, true, Platform::Windows).unwrap_err();
        let norm = err.replace('\\', "/");
        assert!(norm.contains("release/regular/x64"), "{}", err);
        assert!(norm.contains("debug/regular/x64"), "{}", err);
        let _ = fs::remove_dir_all(&cache);
    }
}

#[cfg(test)]
mod prune_tests {
    use super::*;

    #[test]
    fn only_runtime_files_survive() {
        let dir = std::env::temp_dir().join("smd-prune");
        let _ = fs::remove_dir_all(&dir);
        let dll_dir = dir.join("release").join("regular").join("x64");
        fs::create_dir_all(&dll_dir).unwrap();
        fs::write(dll_dir.join("steam_api64.dll"), b"emu").unwrap();
        fs::write(dll_dir.join("steam_api64.pdb"), b"debug").unwrap();
        fs::write(dir.join("emu-win-release-vs26.7z"), b"archive").unwrap();
        fs::write(dir.join(".extracted"), b"tag").unwrap();
        let tools = dir.join("tools");
        fs::create_dir_all(&tools).unwrap();
        fs::write(tools.join("generate_interfaces_x64.exe"), b"tool").unwrap();
        fs::write(dir.join("README.md"), b"docs").unwrap();

        prune_platform_dir(&dir);

        assert!(dll_dir.join("steam_api64.dll").exists());
        assert!(dir.join(".extracted").exists());
        assert!(!dll_dir.join("steam_api64.pdb").exists());
        assert!(!dir.join("emu-win-release-vs26.7z").exists());
        assert!(!tools.join("generate_interfaces_x64.exe").exists());
        assert!(!dir.join("README.md").exists());
        assert!(!tools.exists());
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn linux_libraries_survive() {
        let dir = std::env::temp_dir().join("smd-prune-linux");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("libsteam_api.so"), b"emu").unwrap();
        fs::write(dir.join("notes.txt"), b"docs").unwrap();

        prune_platform_dir(&dir);

        assert!(dir.join("libsteam_api.so").exists());
        assert!(!dir.join("notes.txt").exists());
        let _ = fs::remove_dir_all(&dir);
    }
}

mod asset_pick_tests {
    use super::*;

    fn release_assets(names: &[&str]) -> Vec<serde_json::Value> {
        names
            .iter()
            .map(|n| {
                serde_json::json!({
                    "name": n,
                    "browser_download_url": format!("https://example.invalid/{}", n),
                    "size": 42,
                })
            })
            .collect()
    }

    #[test]
    fn an_exact_asset_name_wins_over_pattern_candidates() {
        let assets = release_assets(&["emu-win-release-x64.7z", "emu-win-release.7z"]);
        let got = pick_asset(
            &assets,
            "emu-win-release.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("emu-win-release.7z")
        );
    }

    #[test]
    fn a_release_asset_wins_over_debug_candidates() {
        let assets = release_assets(&[
            "emu-win-debug-vs22.7z",
            "emu-win-debug-vs26.7z",
            "emu-win-release-vs22.7z",
            "emu-win-release-vs26.7z",
            "migrate_gse-win-vs22.7z",
            "migrate_gse-win.7z",
        ]);
        let got = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("emu-win-release-vs26.7z")
        );
    }

    #[test]
    fn the_newer_toolchain_wins_over_the_older_one() {
        let assets = release_assets(&["emu-win-release-vs22.7z", "emu-win-release-vs26.7z"]);
        let got = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("emu-win-release-vs26.7z")
        );
    }

    #[test]
    fn a_future_toolchain_wins_without_code_changes() {
        let assets = release_assets(&["emu-win-release-vs22.7z", "emu-win-release-vs26.7z", "emu-win-release-vs28.7z"]);
        let got = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("emu-win-release-vs28.7z")
        );
    }

    #[test]
    fn the_older_toolchain_is_used_when_the_newer_one_is_missing() {
        let assets = release_assets(&["emu-win-debug-vs26.7z", "emu-win-release-vs22.7z"]);
        let got = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("emu-win-release-vs22.7z")
        );
    }

    #[test]
    fn a_linux_release_asset_is_found() {
        let assets = release_assets(&["emu-linux-debug.tar.bz2", "emu-linux-release.tar.bz2"]);
        let got = pick_asset(
            &assets,
            "emu-linux-release.tar.bz2",
            "linux",
            ".tar.bz2",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("emu-linux-release.tar.bz2")
        );
    }

    #[test]
    fn matching_is_case_insensitive() {
        let assets = release_assets(&["EMU-WIN-RELEASE-VS26.7Z"]);
        let got = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap();
        assert_eq!(
            got.get("name").and_then(|v| v.as_str()),
            Some("EMU-WIN-RELEASE-VS26.7Z")
        );
    }

    #[test]
    fn a_wrong_extension_is_never_matched() {
        let assets = release_assets(&["emu-win-release-vs26.zip"]);
        let err = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap_err();
        assert!(err.contains("emu-win-release-vs26.zip"), "{}", err);
    }

    #[test]
    fn a_debug_only_release_is_reported_as_missing() {
        let assets = release_assets(&["emu-win-debug-vs26.7z", "emu-linux-release.tar.bz2"]);
        let err = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap_err();
        assert!(err.contains("emu-win-release-vs26.7z"), "{}", err);
        assert!(err.contains("emu-win-debug-vs26.7z"), "{}", err);
    }

    #[test]
    fn a_missing_asset_names_everything_the_release_has() {
        let assets = release_assets(&["README.md", "emu-linux-release.tar.bz2"]);
        let err = pick_asset(
            &assets,
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap_err();
        assert!(err.contains("emu-win-release-vs26.7z"), "{}", err);
        assert!(err.contains("README.md"), "{}", err);
        assert!(err.contains("emu-linux-release.tar.bz2"), "{}", err);
    }

    #[test]
    fn an_empty_release_reports_that_nothing_is_available() {
        let err = pick_asset(
            &[],
            "emu-win-release-vs26.7z",
            "win",
            ".7z",
            &["release"],
            &["debug"],
        )
        .unwrap_err();
        assert!(err.contains("available: none"), "{}", err);
    }
}
