name: Build Linux (Test)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7

      - name: Build AppImage
        uses: ./.github/actions/linux-appimage
        with:
          channel: dev-local
          git-sha: ${{ github.sha }}

      - name: Upload AppImage
        uses: actions/upload-artifact@v7
        with:
          name: linux-appimage
          path: "Steam Manifest Downloader_*_amd64.AppImage"
